from sqlalchemy import JSON, TIMESTAMP, BigInteger, Boolean, Column, String
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class Page(Base):
    __tablename__ = "pages"

    id = Column(String, primary_key=True)
    url = Column(String)
    icon = Column(JSON)
    cover = Column(JSON)
    object = Column(JSON)
    parent = Column(JSON)
    archived = Column(Boolean)
    created_by = Column(JSON)
    properties = Column(JSON)
    public_url = Column(String)
    created_time = Column(TIMESTAMP)
    last_edited_by = Column(JSON)
    last_edited_time = Column(TIMESTAMP)
    _airbyte_raw_id = Column(String(36), nullable=False)
    _airbyte_extracted_at = Column(TIMESTAMP, nullable=False)
    _airbyte_generation_id = Column(BigInteger)
    _airbyte_meta = Column(JSON, nullable=False)


class Block(Base):
    __tablename__ = "blocks"

    id = Column(String, primary_key=True)
    pdf = Column(JSON)
    code = Column(JSON)
    file = Column(JSON)
    type = Column(JSON)
    embed = Column(JSON)
    image = Column(JSON)
    quote = Column(JSON)
    table = Column(JSON)
    to_do = Column(JSON)
    video = Column(JSON)
    column = Column(JSON)
    object = Column(JSON)
    parent = Column(JSON)
    toggle = Column(JSON)
    callout = Column(JSON)
    divider = Column(JSON)
    archived = Column(Boolean)
    bookmark = Column(JSON)
    equation = Column(JSON)
    template = Column(JSON)
    heading_1 = Column(JSON)
    heading_2 = Column(JSON)
    heading_3 = Column(JSON)
    paragraph = Column(JSON)
    table_row = Column(JSON)
    breadcrumb = Column(JSON)
    child_page = Column(JSON)
    created_by = Column(JSON)
    column_list = Column(JSON)
    unsupported = Column(JSON)
    created_time = Column(TIMESTAMP)
    has_children = Column(Boolean)
    link_preview = Column(JSON)
    link_to_page = Column(JSON)
    synced_block = Column(JSON)
    child_database = Column(JSON)
    last_edited_by = Column(JSON)
    last_edited_time = Column(TIMESTAMP)
    table_of_contents = Column(JSON)
    bulleted_list_item = Column(JSON)
    numbered_list_item = Column(JSON)
    _airbyte_raw_id = Column(String(36), nullable=False)
    _airbyte_extracted_at = Column(TIMESTAMP, nullable=False)
    _airbyte_generation_id = Column(BigInteger)
    _airbyte_meta = Column(JSON, nullable=False)


class Database(Base):
    __tablename__ = "databases"

    id = Column(String, primary_key=True)
    url = Column(String)
    icon = Column(JSON)
    cover = Column(JSON)
    title = Column(JSON)
    object = Column(JSON)
    parent = Column(JSON)
    archived = Column(Boolean)
    is_inline = Column(Boolean)
    created_by = Column(JSON)
    properties = Column(JSON)
    public_url = Column(String)
    description = Column(JSON)
    created_time = Column(TIMESTAMP)
    last_edited_by = Column(JSON)
    last_edited_time = Column(TIMESTAMP)
    _airbyte_raw_id = Column(String(36), nullable=False)
    _airbyte_extracted_at = Column(TIMESTAMP, nullable=False)
    _airbyte_generation_id = Column(BigInteger)
    _airbyte_meta = Column(JSON, nullable=False)
