name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml mkdocs mkdocs-material mkdocstrings

      - name: Generate Documentation
        run: python docs/create_docs.py 

      - name: Check for changes in docs or mkdocs.yml
        id: check_changes
        run: |
          if git diff --quiet docs/ mkdocs.yml; then
            echo "Changes detected in docs or mkdocs.yml"
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in docs or mkdocs.yml"
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Docs
        if: env.no_changes == 'false'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs/ mkdocs.yml
          git commit -m "Update documentation"
          git push origin main

      - name: Deploy to GitHub Pages
        if: env.no_changes == 'false'
        run: mkdocs gh-deploy --force
