name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml mkdocs mkdocs-material mkdocstrings

      - name: Generate Documentation
        run: python docs/create_docs.py 

      - name: Check for changes in docs
        id: check_changes
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo $(git diff)
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Docs
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs/ mkdocs.yml
          git commit -m "Update documentation"
          git push origin main

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.changes == 'true'
        run: mkdocs gh-deploy --force
