name: Generate Docs

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-docs:
    name: Generate Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Generate Documentation
        run: python docs/create_docs.py 

      # TODO: add commit/publishing to gh pages
      # - name: Commit and Push Docs
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     git config --global user.name "${{ github.actor }}"
      #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add docs/
      #     git commit -m "Update documentation"
      #     git push origin main

      # - name: Deploy to GitHub Pages
      #   if: github.ref == 'refs/heads/main'
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs
